In [1]:
123

123

# Data Analysis
## data1
### data2
#### data3
###### data4
###### data 5

data

iam in **bold** style

iam in # bold style

i am in ***italic+bold*** style

- point1
* point 2


- main_point
    - point
        - point
            - point
                * Point

#### order 
1. point
3. point
3. Point

[python](https://www.python.org/downloads/)


col1 | col2 
--|--
1|2
2|3

![](https://tse3.mm.bing.net/th?id=OIP.bNomfe6uhjHEDlPb8bYqiAHaFj&pid=Api&P=0&w=231&h=174)

![](python.jpg)



In [2]:
123456

123456

In [3]:
xnhcznhcvnh

NameError: name 'xnhcznhcvnh' is not defined

In [4]:
"hjfgdjhf"

'hjfgdjhf'

## What's Numpy?

scipy

Numerical Python, popularly known as Numpy has been designed to carry out mathematical computations at a faster and easier rate.

### How to install Numpy ?

```pip install numpy```

#### Why Numpy when we have “Lists” ?

- Size – Numpy data structures take less space
- Performance – They are inherently faster than lists.
- Functionality – Scipy and Numpy have optimized functions.
- Vectorization of the operations 


Ndarray is multidimensional object which can contain only single data type objects.


### Creating arrays 
- using List 
- using Tuples

### Methods  in Numpy

**Attributes :**  
- shape
- size
- ndim
- len
- dtype
- dtype.name

**Slicing and Dicing & indexing :**
- subsets
- selecting rows & columns
- Extracting single element
- Fancy Indexing


**Arthmetic Operations :**
- add
- subtract
- multiply
- divide
- exp
- log
- sin
- cos
- tan
- sqrt
**Iterating array**
- nditer


**Aggregations :**
- sum
- min(axis = 1)
- max(axis = 0)
- median
- std

**Initial Placeholders :**
creating different arrays using default methods
- zeros
- ones
- full
- eye
- linspace
- empty
- random.random
- arange
- random.randint
- logspace
- choice 
- Nonzero
- 

**Sorting Arrays :**
- sort
- sort(axis =0)



**Array Manipulation :**
- Transposing
- changing shape (ravel & reshape)
- adding/ removing elemnts
    - append
    - insert
    - delete
- Combining array
    - concatenate
    - hstack
    - vstack
    - ravel
    - flatten
    
**Saving & Loading files :**
- save('file_name', array)
- load('file_name.npy')

 

# List
- sequential data
- collection of data , and enclosed with []

In [15]:
li = [1,23,34,56] # iterable 
# more time to excute 
# slow 
# not verctization 
type(li)
for i in li:
    print(i*5)

5
115
170
280


In [6]:
li*5

[1, 23, 34, 56, 1, 23, 34, 56, 1, 23, 34, 56, 1, 23, 34, 56, 1, 23, 34, 56]

In [7]:
import math

In [9]:
len(dir(math))

60

In [10]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [11]:
import numpy 

In [12]:
len(dir(numpy))

622

In [14]:
pip install numpy

In [17]:
import numpy as np
n = [345,4,56,6]
np.array(n)*5

array([1725,   20,  280,   30])

In [18]:
# import library 

import numpy as np


In [19]:
np.__version__

'1.18.5'

In [22]:
import sys
sys.version

'3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'

In [23]:
# Creating 0-D numpy array

a1 = np.array(420)
a1

array(420)

In [24]:
a1.ndim

0

In [25]:
# creating 1-D array
# 1D - list
a2 = np.array([1,2,3,4,5,6])
a2

array([1, 2, 3, 4, 5, 6])

In [26]:
a2.ndim

1

In [27]:
# Creating 2-D array
# collection of 1-D array

a3 = np.array([[1,2,3],[4,5,6]])
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a3.ndim

2

In [29]:
a3.shape # rows,  columns

(2, 3)

shape 
ndim

array() --- method 


function vs methods

-  function : set of code
-  Methods : function inside class 

In [30]:
len('lavanya')  # function
print("apssdc") # functions
np.array()   # Methods

7

In [33]:
# Creating 3-D array
# collection of 2-D data
a4 = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])
a4

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [32]:
a4.ndim

3

In [34]:
a4.shape

(2, 2, 3)

In [40]:
# creating Multi-D array

a5 = np.array([1,2,3,4,5],ndmin = 5)
a5

array([[[[[1, 2, 3, 4, 5]]]]])

In [39]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [41]:
a5.ndim

5

In [42]:
# tuple is immutable --  we can't change anything
# List is mutable -- we can change, modify, del, add,insert..  etc
a6 = np.array(((12,3,4,4),(5,6,7,8)))
a6

array([[12,  3,  4,  4],
       [ 5,  6,  7,  8]])

In [43]:
a6.dtype

dtype('int32')

In [44]:
# array is homogeneous -- having same type of data
# it converted by higher priority data type

a7 = np.array([12,34,4.5])
a7

array([12. , 34. ,  4.5])

In [45]:
a8 = np.array((23,4,5.6,"a","b"))
a8

array(['23', '4', '5.6', 'a', 'b'], dtype='<U32')

In [47]:
a8.dtype.name

'str1024'

In [48]:
a8.size

5

In [49]:
a8.itemsize

128

# Slicing

In [50]:
arr = np.array([[12,3,4,5,6],[12,34,45,5,6]])
arr

array([[12,  3,  4,  5,  6],
       [12, 34, 45,  5,  6]])

In [51]:
arr[:: , ::]

array([[12,  3,  4,  5,  6],
       [12, 34, 45,  5,  6]])

In [52]:
li

[1, 23, 34, 56]

In [53]:
li[0]

1

In [54]:
li[-1]

56

In [55]:
li[0:2]  
# start value (inclusive), 
# end value(exclusive)
# step value

[1, 23]

In [56]:
li

[1, 23, 34, 56]

In [62]:
li[2:]

[34, 56]

In [64]:
arr[:: , ::]

array([[12,  3,  4,  5,  6],
       [12, 34, 45,  5,  6]])

In [65]:
arr.shape

(2, 5)

In [66]:
arr[0:1]

array([[12,  3,  4,  5,  6]])

In [68]:
arr[:,2:3]

array([[ 4],
       [45]])

In [69]:
arr[::,4:5]

array([[6],
       [6]])

In [70]:
arr[:,-1]

array([6, 6])

In [71]:
arr[0:1,1:3]

array([[3, 4]])

In [73]:
arr[1:,:2]

array([[12, 34]])

In [75]:
arr[1:,2:3]

array([[45]])

In [77]:
arr[0:1 , 0:1 ]

array([[12]])

In [81]:
arr[1, 4]

6

In [79]:
arr

array([[12,  3,  4,  5,  6],
       [12, 34, 45,  5,  6]])

In [84]:
arr[-1,-1]

6

In [85]:
arr[-1]

array([12, 34, 45,  5,  6])

In [88]:
arr[-2:-1,-4:-2]

array([[3, 4]])

In [92]:
arr[-1:,-4:-2]

array([[34, 45]])

In [97]:
arr[::,-1]

array([6, 6])

In [98]:
arr[-1,-3]

45

In [100]:
arr[-1:,:-4]

array([[12]])

In [101]:
arr[-1,-1]

6

# Indexing

range(start,end, step)

In [106]:
ar = np.array([[[12,3,43],[23,45,6]],[[2,34,5],[34,56,6]]])
ar

array([[[12,  3, 43],
        [23, 45,  6]],

       [[ 2, 34,  5],
        [34, 56,  6]]])

In [108]:
ar[1:2]

array([[[ 2, 34,  5],
        [34, 56,  6]]])

In [110]:
li = [23,4,5,56,7,87,8,8]
li[1:6:2]

[4, 56, 87]

In [120]:
ar[1][:2,:2]

array([[ 2, 34],
       [34, 56]])

**Arthmetic Operations :**
- add
- subtract
- multiply
- divide
- exp
- log
- sin
- cos
- tan
- sqrt

In [121]:
ar1 = np.array((1,2,3,4,5))
ar1*10

array([10, 20, 30, 40, 50])

In [122]:
ar2 = np.array([1,2,3,3,2])
np.add(ar1,ar2)

array([2, 4, 6, 7, 7])

In [123]:
np.subtract(ar2,ar1)

array([ 0,  0,  0, -1, -3])

In [124]:
np.multiply(ar2,8)

array([ 8, 16, 24, 24, 16])

In [125]:
np.divide(ar1,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [126]:
np.log(ar1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [127]:
np.tan(ar1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [128]:
np.cos(ar2)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.9899925 , -0.41614684])

In [129]:
np.abs(-1)

1

In [130]:
np.exp(2)

7.38905609893065

In [131]:
np.sqrt(16)

4.0

In [132]:
np.ceil(90.8)

91.0

In [135]:
np.floor(90.6)

90.0

**Iterating array**
- nditer

In [136]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [139]:
for val in arr2:
    for v in val:
        print(v)

1
2
3
4
4
5
6
7


In [140]:
for val in np.nditer(arr2):
    print(val)

1
2
3
4
4
5
6
7


**Aggregations :**
- sum
- min(axis = 1)
- max(axis = 0)
- median
- std

In [141]:
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [142]:
sum(arr2)

array([ 5,  7,  9, 11])

In [145]:
np.sum(arr2,axis = 1)  # columns 

array([10, 22])

In [146]:
np.sum(arr2,axis = 0) # row addition

array([ 5,  7,  9, 11])

In [147]:
np.sum(arr2)

32

In [148]:
np.mean(arr2)

4.0

In [150]:
arr2.size

8

In [151]:
np.median(arr2)

4.0

In [152]:
np.std(arr2)

1.8708286933869707

In [153]:
np.var(arr2)

3.5

In [154]:
np.min(arr2)

1

In [155]:
np.max(arr2)

7

In [156]:
np.argmin(arr2)

0

In [157]:
np.argmax(arr2)

7

In [158]:
arr2.max()

7

In [159]:
np.pi

3.141592653589793

In [160]:
arr2


array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

**Initial Placeholders :**
creating different arrays using default methods
- zeros
- ones
- full
- eye
- linspace
- empty
- random.random
- arange
- random.randint
- logspace
- choice 
- Nonzero

In [163]:
b1 = np.zeros(10, dtype = "int")
b1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [162]:
b1.dtype

dtype('float64')

In [164]:
b2 = np.zeros((5,5))
b2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [167]:
b3 = np.ones((3,4), dtype = "bool")
b3
# int,float, str, bool

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [168]:
b4 = np.full((4,5), 7)
b4

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [170]:
b5 = np.eye(7)
b5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [171]:
b6 = np.arange(1,100,10) # start value, end value, step
b6

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [172]:
b7 = np.linspace(1,100,10) # start value, end , length
b7

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [173]:
b8 = np.linspace(1,10,10) # start value, end , no. of parts/length of array
b8

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [177]:
b7 = np.arange(1,10,10)
b7

array([1])

In [192]:
b8 = np.empty(9)
b8


array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 7.90505033e-321, 1.54481294e-311, 1.54481294e-311,
       1.54630649e-311])

In [184]:
b9 = np.random.random(10)
b9 # 0-1

array([0.55846375, 0.14587005, 0.84315693, 0.75208889, 0.78280518,
       0.30100841, 0.61078691, 0.15332431, 0.24976113, 0.39483448])

In [191]:
b10 = np.random.randint(1,1000,3)
b10

array([343,  50, 792])

In [194]:
b11 = np.random.choice(['kamal',"gowtham","swetha","vikas"])
b11

'swetha'

In [197]:
b12 = np.nonzero([1,2,0,5,0,34,0,35,1,35])
b12 # non zero element index positions

(array([0, 1, 3, 5, 7, 8, 9], dtype=int64),)

# Task

1 1 1 1 1
1 0 0 0 1
1 0 7 0 1
1 0 0 0 1
1 1 1 1 1

In [204]:
t = np.ones((5,5), dtype = "int")
t[1:4,1:4] = 0
t[2,2] = 7
t

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 7, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

**Sorting Arrays :**
- sort
- sort(axis =0)



**Array Manipulation :**
- Transposing
- changing shape (ravel & reshape)
- adding/ removing elemnts
    - append
    - insert
    - delete
- Combining array
    - concatenate
    - hstack
    - vstack
    - ravel
    - flatten

In [205]:
b10 = np.array([1,2,34,2,3,4,2,3,5])
b10

array([ 1,  2, 34,  2,  3,  4,  2,  3,  5])

In [206]:
# variable 
# space, spl characters, number 

In [207]:
b10.sort()

In [208]:
b10

array([ 1,  2,  2,  2,  3,  3,  4,  5, 34])

In [217]:
ar = np.array([[[12,3,43],[23,45,6]],[[2,34,5],[34,56,6]]])
ar

array([[[12,  3, 43],
        [23, 45,  6]],

       [[ 2, 34,  5],
        [34, 56,  6]]])

In [218]:
ar.sort(axis = 0)
ar

array([[[ 2,  3,  5],
        [23, 45,  6]],

       [[12, 34, 43],
        [34, 56,  6]]])

In [219]:
ar.sort(axis = 1)
ar

array([[[ 2,  3,  5],
        [23, 45,  6]],

       [[12, 34,  6],
        [34, 56, 43]]])

In [221]:
ar.shape

(2, 2, 3)

In [222]:
ar.T.shape  

(3, 2, 2)

In [223]:
ar.T

array([[[ 2, 12],
        [23, 34]],

       [[ 3, 34],
        [45, 56]],

       [[ 5,  6],
        [ 6, 43]]])

In [227]:
# ravel & flatten - converts multi- D to single -D 

ar_r = np.ravel(ar)

In [228]:
ar_f = ar.flatten()

In [234]:
ar_r[1] = 100
ar_f[2] = 100

In [235]:
ar_r

array([  2, 100,   5,  23,  45,   6,  12,  34,   6,  34,  56,  43])

In [236]:
ar

array([[[  2, 100,   5],
        [ 23,  45,   6]],

       [[ 12,  34,   6],
        [ 34,  56,  43]]])

In [237]:
ar_f

array([  2, 100, 100,  23,  45,   6,  12,  34,   6,  34,  56,  43])

In [238]:
ar

array([[[  2, 100,   5],
        [ 23,  45,   6]],

       [[ 12,  34,   6],
        [ 34,  56,  43]]])

In [240]:
ar.shape # 12

(2, 2, 3)

In [245]:
ar.reshape((1,6,2))

array([[[  2, 100],
        [  5,  23],
        [ 45,   6],
        [ 12,  34],
        [  6,  34],
        [ 56,  43]]])

In [248]:
x = np.array([234,5,6])
del x

In [249]:
x

NameError: name 'x' is not defined

In [256]:
x = np.array([234,5,6])
np.delete(x,0)

array([5, 6])

In [258]:
np.insert(x,3,12)

array([234,   5,   6,  12])

# Task 

* Generate jan Month dates 
* Display 8x8 matrix checkboard pattern
* Display Todays date 

In [260]:
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
      Input array.
    obj : slice, int or array of ints
      Indicate indices of sub-arrays to remove along the specified axis.
    axis : int, optional
      The axis along which to delete the subarray defined by `obj`.
      If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    append : Append elements at the end of an array.
    
    Notes
    -----
    Often it is preferable to use a boolean mask. For 